
    <table id="x"
    data-toggle="table"
    data-striped=true
    data-url="tab3_pagination.asp"
    data-search="true"
    data-show-refresh="true"
    data-pagination="true"
    data-sort-name="date_rec"
    data-sort-order="desc"
    data-page-size="50"
    data-side-pagination="server"
    data-height="555">

     <thead>
         <tr>

             <th data-field="id" data-visible="false">
                 id
             </th>
             <th data-field="cust_name" data-sortable="true">
                Customer
             </th>
             
             <th data-field="date_rec" data-sortable="true">
                DateRec
             </th>
             <th data-field="amount" data-sortable="true">
                Amount
             </th>
         </tr>
     </thead>
 </table>
</div>
