//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about_logo {
            get {
                object obj = ResourceManager.GetObject("about-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Delete_icon {
            get {
                object obj = ResourceManager.GetObject("Button-Delete-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Delete_iconOther {
            get {
                object obj = ResourceManager.GetObject("Button-Delete-iconOther", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy16 {
            get {
                object obj = ResourceManager.GetObject("copy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///@session_start();
        ///
        ///if (!isset($_SESSION[&quot;id&quot;]) || empty($_POST[&apos;*PK*&apos;])) {
        ///	echo json_encode(null);
        ///	exit ;
        ///}
        ///
        ///
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db = connect();
        ///
        ///$sql = &quot;DELETE FROM `*table*` WHERE *PK*=:*PK*&quot;;
        ///$sth = $db-&gt;prepare($sql);
        ///$sth-&gt;bindValue(&apos;:*PK*&apos;, $_POST[&apos;*PK*&apos;]);
        ///	
        ///$sth-&gt;execute();
        ///
        ///echo $sth-&gt;errorCode(); 
        ///?&gt;.
        /// </summary>
        internal static string CRUD2template_delete {
            get {
                return ResourceManager.GetString("CRUD2template_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///@session_start();
        ///
        ///if (!isset($_SESSION[&quot;id&quot;]) || empty($_POST[&apos;*PK*&apos;])) {
        ///	echo json_encode(null);
        ///	exit ;
        ///}
        ///
        ///
        ///try {
        ///	include (&apos;config.php&apos;);
        ///
        ///	$db = connect();
        ///
        ///	$r= getRow($db, &quot;SELECT *select* FROM *table* where *PK*=?&quot;, array($_POST[&apos;*PK*&apos;]));
        ///
        ///    //unicode
        ///    header(&quot;Content-Type: application/json&quot;, true);
        ///	echo json_encode($r);
        ///
        ///	
        ///} catch (exception $e) {
        ///    echo json_encode(null);
        ///}
        ///?&gt;.
        /// </summary>
        internal static string CRUD2template_fetch {
            get {
                return ResourceManager.GetString("CRUD2template_fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///@session_start();
        ///
        ///if (!isset($_SESSION[&quot;id&quot;])) {
        ///	header(&quot;Location: login.php&quot;);
        ///	exit ;
        ///}
        ///
        ///// include DB
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db       = connect();
        ///
        ///#FKs#
        ///?&gt;
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///		&lt;title&gt;
        ///			Bootstrap Table
        ///		&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;css/bootstrap.min.css&quot;&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD2template_main {
            get {
                return ResourceManager.GetString("CRUD2template_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///						&lt;th data-field=&quot;*field*&quot; data-visible=&quot;*fieldv*&quot;&gt;
        ///							*field*
        ///						&lt;/th&gt;
        ///						.
        /// </summary>
        internal static string CRUD2template_main_TABLE_Item {
            get {
                return ResourceManager.GetString("CRUD2template_main_TABLE_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///@session_start();
        ///
        ///if (!isset($_SESSION[&quot;id&quot;])) {
        ///    echo json_encode(null);
        ///    exit ;
        ///}
        ///
        ///
        ///// include your code to connect to DB.
        ///include (&apos;config.php&apos;);
        ///
        ///$table_columns = array(
        ///#cols#
        ///);
        ///
        ///$conn     = connect();
        ///
        ///if (!is_numeric($_GET[&quot;limit&quot;]) || !is_numeric($_GET[&quot;offset&quot;]))
        ///{
        ///	echo &quot;error&quot;;
        ///	exit;
        ///}
        ///
        ///$limit = $_GET[&quot;limit&quot;];
        ///$offset= $_GET[&quot;offset&quot;];
        ///
        ///
        ///$sql=&quot;select #select_cols# from #table# #joins#&quot;;
        ///$count_query_sql = &quot;select count(*) from #table#&quot;;
        ///
        ///
        ///////////// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD2template_pagination {
            get {
                return ResourceManager.GetString("CRUD2template_pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///@session_start();
        ///
        ///if (!isset($_SESSION[&quot;id&quot;])) {
        ///    echo json_encode(null);
        ///    exit ;
        ///}
        /// 
        ///if (#validation#){
        ///	echo &quot;error010101010&quot;;
        ///	return;
        ///}
        /// 
        /////DB
        ///require_once (&apos;config.php&apos;);
        /// 
        ///$db = connect();
        /// 
        ///#checkboxes#
        ///
        ///#dtptimes#
        ///
        ///if(isset($_POST[&apos;#tblname#FORM_updateID&apos;]) &amp;&amp; !empty($_POST[&apos;#tblname#FORM_updateID&apos;]))
        ///{
        ///	$sql = &quot;UPDATE #tblname# set #updateVAL# where #updateWhere#=:#updateWhere#&quot;;
        ///	$stmt = $db-&gt;prepare($sql);
        ///	$stmt-&gt;bindValue(&apos;:#updateWhere#&apos; , $_POST[&apos;#tblnam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD2template_save {
            get {
                return ResourceManager.GetString("CRUD2template_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///require_once &apos;../vendor/general.php&apos;;
        ///require_once &apos;../vendor/VendorGetter.php&apos;;
        ///
        ///if (!isset($_POST[&apos;action&apos;])){
        ///	ReportJS(1, &apos;No valid parameter!&apos;);
        ///	exit;
        ///}
        ///
        ///////////////////ACTIONS
        ///$action = $_POST[&apos;action&apos;];
        ///
        ///switch ($action) {
        ///	case &apos;GetVendor{tbl}JS&apos; :
        ///		GetVendor{tbl}JS();
        ///		break;
        ///{swGetRecordDetails}
        ///	case &apos;GetVendor{tbl}CRON&apos; :
        ///		//todo
        ///		break;
        ///	case &apos;FillGrid&apos; :
        ///		FillGrid();
        ///		break;
        ///	default :
        ///		ReportJS(2, &apos;No action defined!&apos;);
        ///		exit;
        ///}
        ///
        ///{GetRecordDetails [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD3template_helper {
            get {
                return ResourceManager.GetString("CRUD3template_helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //this function gets executed after base record inserted
        ///function {tbl}AfterBaseRecordInsert($db, $baseTableID, $data){
        ///
        ///    if ($data == null)
        ///        return;
        ///
        ///    $ignored = 0;
        ///    $failed = 0;
        ///    $nullrec = 0;
        ///    $added = 0;
        ///
        ///    $insertSQL = &apos;INSERT INTO `{tblREF}` ({helperTableCOLScsv}) VALUES (:{helperTableCOLSbind})&apos;;
        ///
        ///	//unlimited depth &apos;x&apos; =&gt; array(&apos;coverage&apos;, &apos;fixtures&apos;, &apos;x&apos;),
        ///	//key = dbase field, array = object direction to JSON field
        ///    $insertSQLFields = array(
        ///{vendorGetter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD3template_helper_AfterBaseRecordInsert {
            get {
                return ResourceManager.GetString("CRUD3template_helper_AfterBaseRecordInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetRecordDetails{tbl}JS(){
        ///
        ///    $recID = $_POST[&apos;recID&apos;];
        ///
        ///    $db = new dbase();
        ///    $db-&gt;connect_mysql();
        ///
        ///    echo json_encode($db-&gt;getSet(&quot;select * from {tblREF} where {pk}=$recID&quot;, null));
        ///}.
        /// </summary>
        internal static string CRUD3template_helper_GetRecordDetails {
            get {
                return ResourceManager.GetString("CRUD3template_helper_GetRecordDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     case &apos;GetRecordDetails{tbl}JS&apos; :
        ///        GetRecordDetails{tbl}JS();
        ///        break;.
        /// </summary>
        internal static string CRUD3template_helper_Switch_GetRecordDetails {
            get {
                return ResourceManager.GetString("CRUD3template_helper_Switch_GetRecordDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///		&lt;title&gt;PipisCrew&lt;/title&gt;
        ///
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback&quot;&gt;
        ///
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;assets/bootstrap.min.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;assets/bootstrap-table.min.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;assets/fontawessome.css&quot;&gt;
        ///
        ///		&lt;script src=&quot;assets/jquery.m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD3template_index {
            get {
                return ResourceManager.GetString("CRUD3template_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       case &apos;#{0}&apos; :
        ///      if (!$(&quot;#table{0}&quot;).hasClass(&apos;table-bordered&apos;))
        ///            RefreshGrid{0}();
        ///      else 
        ///            $(&apos;#table{0}&apos;).bootstrapTable(&apos;resetView&apos;);
        ///      break;
        ///.
        /// </summary>
        internal static string CRUD3template_index_JS_gridload {
            get {
                return ResourceManager.GetString("CRUD3template_index_JS_gridload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         &lt;li class=&quot;nav-item&quot;&gt;
        ///          &lt;button class=&quot;nav-link{0}&quot; data-bs-toggle=&quot;tab&quot; data-bs-target=&quot;#{1}&quot; type=&quot;button&quot; role=&quot;tab&quot;&gt;{1}&lt;/button&gt;
        ///        &lt;/li&gt;
        ///.
        /// </summary>
        internal static string CRUD3template_index_tab {
            get {
                return ResourceManager.GetString("CRUD3template_index_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;tab-pane fade{0}&quot; role=&quot;tabpanel&quot; id=&quot;{1}&quot;&gt;
        ///&lt;?php include (&quot;pages/{1}.php&quot;); ?&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string CRUD3template_index_tab_content {
            get {
                return ResourceManager.GetString("CRUD3template_index_tab_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ====================================================================================== {tbl} ====================================================================================== --&gt;
        ///&lt;script&gt;
        ///
        ///    function RefreshGrid{tbl}(){
        ///{transformJS}
        ///    }
        ///	
        ///	//Bootstrap table - #extra parameter# to identify is going for pagination
        ///	function queryParams(params) {
        ///		// ref - https://examples.bootstrap-table.com/index.html#options/query-params.html#view-source
        ///		params.action = &apos;FillGrid&apos;;
        ///		return para [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD3template_page {
            get {
                return ResourceManager.GetString("CRUD3template_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             $(&quot;#table{tbl}&quot;).bootstrapTable({
        ///
        ///                onExpandRow: function (index, row, $detail) {
        ///
        ///                    $.ajax({
        ///                            url : &apos;entities/{tbl}Helper.php&apos;,
        ///                            dataType : &apos;json&apos;,
        ///                            type : &apos;POST&apos;,
        ///                            data : { &apos;action&apos; : &apos;GetRecordDetails{tbl}JS&apos;, &apos;recID&apos; : row.id },
        ///                            success : function(data) {
        ///                                
        ///                            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD3template_page_w_subtable {
            get {
                return ResourceManager.GetString("CRUD3template_page_w_subtable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;template&gt;
        ///  &lt;v-app&gt;
        ///    &lt;v-app-bar app color=&quot;primary&quot; dark&gt;
        ///      &lt;v-tabs align-with-title&gt;
        ///{0}
        ///      &lt;/v-tabs&gt;
        ///
        ///      &lt;v-btn icon @click=&quot;switchTheme&quot;&gt;
        ///        &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot; role=&quot;img&quot; aria-hidden=&quot;true&quot; class=&quot;v-icon__svg&quot;&gt;&lt;path d=&quot;M12,19.58V19.58C10.4,19.58 8.89,18.96 7.76,17.83C6.62,16.69 6,15.19 6,13.58C6,12 6.62,10.47 7.76,9.34L12,5.1M17.66,7.93L12,2.27V2.27L6.34,7.93C3.22,11.05 3.22,16.12 6.34,19.24C7.9,20.8 9.95,21.58 12,21.58C14.05,21.58 16.1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD4appVueMain {
            get {
                return ResourceManager.GetString("CRUD4appVueMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;template&gt;
        ///  &lt;v-dialog
        ///    v-model=&quot;showModal&quot;
        ///    fullscreen
        ///    hide-overlay
        ///    transition=&quot;dialog-bottom-transition&quot;
        ///  &gt;
        ///    &lt;v-container
        ///      v-if=&quot;loading&quot;
        ///      fluid
        ///      fill-height
        ///      style=&quot;background-color: rgba(255, 255, 255, 0.5)&quot;
        ///    &gt;
        ///      &lt;v-layout justify-center align-center&gt;
        ///        &lt;v-progress-circular indeterminate color=&quot;primary&quot;&gt;
        ///        &lt;/v-progress-circular&gt;
        ///      &lt;/v-layout&gt;
        ///    &lt;/v-container&gt;
        ///    &lt;v-card&gt;
        ///      &lt;v-toolbar dark color=&quot;primary&quot;&gt;
        ///        &lt;v- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD4details {
            get {
                return ResourceManager.GetString("CRUD4details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               &lt;v-autocomplete
        ///                v-model=&quot;privateRecord.{0}&quot;
        ///                :items=&quot;{0}Items&quot;
        ///                :rules=&quot;[() =&gt; !!privateRecord.{0} || &apos;This field is required&apos;]&quot;
        ///                item-text=&quot;{1}&quot;
        ///                item-value=&quot;{2}&quot;
        ///                label=&quot;Select&quot;
        ///                single-line
        ///                required
        ///              &gt;&lt;/v-autocomplete&gt;.
        /// </summary>
        internal static string CRUD4detailsAutoCompleteElement {
            get {
                return ResourceManager.GetString("CRUD4detailsAutoCompleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     get{0}() {
        ///      let formData = new FormData();
        ///      formData.append(&quot;action&quot;, &quot;GetRecords{0}&quot;);
        ///
        ///      const requestOptions = {
        ///        method: &quot;POST&quot;,
        ///        cache: &quot;no-cache&quot;,
        ///        body: formData,
        ///      };
        ///
        ///      return fetch(&quot;/api/{1}API.php&quot;, requestOptions);
        ///    },
        ///.
        /// </summary>
        internal static string CRUD4detailsGetRefTable {
            get {
                return ResourceManager.GetString("CRUD4detailsGetRefTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           this.{0}Items = r[{2}].map((item) =&gt; {
        ///            return { ...new {1}(item) };
        ///          });
        ///.
        /// </summary>
        internal static string CRUD4detailsREFTablesPromise {
            get {
                return ResourceManager.GetString("CRUD4detailsREFTablesPromise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               &lt;v-switch
        ///                v-model=&quot;privateRecord.{0}&quot;
        ///                label=&quot;{0}&quot;
        ///              &gt;&lt;/v-switch&gt;.
        /// </summary>
        internal static string CRUD4detailsSwitchElement {
            get {
                return ResourceManager.GetString("CRUD4detailsSwitchElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               &lt;v-text-field
        ///                v-model=&quot;privateRecord.{0}&quot;
        ///                label=&quot;{0}&quot;
        ///                counter=&quot;{1}&quot;
        ///                :rules=&quot;[() =&gt; !!( {2}privateRecord.{0}.length &lt;= {1} ) || &apos;{0} must be less than {1} characters&apos;,]&quot;
        ///                {3}
        ///              &gt;&lt;/v-text-field&gt;.
        /// </summary>
        internal static string CRUD4detailsTextElement {
            get {
                return ResourceManager.GetString("CRUD4detailsTextElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               &lt;vdatepickerex
        ///                caption=&quot;{0}&quot;
        ///                :required=&quot;{1}&quot;
        ///                :setTodayWhenNew=&quot;true&quot;
        ///                v-model=&quot;privateRecord.{0}&quot;
        ///                :value.sync=&quot;privateRecord.{0}&quot;
        ///              /&gt;.
        /// </summary>
        internal static string CRUD4detailsVDateElement {
            get {
                return ResourceManager.GetString("CRUD4detailsVDateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               &lt;vdatetimepickerex
        ///                caption=&quot;{0}&quot;
        ///                :required=&quot;{1}&quot;
        ///                v-model=&quot;privateRecord.{0}&quot;
        ///                :value.sync=&quot;privateRecord.{0}&quot;
        ///              /&gt;.
        /// </summary>
        internal static string CRUD4detailsVDateTimeElement {
            get {
                return ResourceManager.GetString("CRUD4detailsVDateTimeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               &lt;vnumber
        ///                v-model=&quot;privateRecord.{0}&quot;
        ///                caption=&quot;{0}&quot;
        ///                :dec=&quot;true&quot;
        ///                :value.sync=&quot;privateRecord.{0}&quot;
        ///              &gt;&lt;/vnumber&gt;.
        /// </summary>
        internal static string CRUD4detailsVNumberDEC {
            get {
                return ResourceManager.GetString("CRUD4detailsVNumberDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               &lt;vnumber
        ///                v-model=&quot;privateRecord.{0}&quot;
        ///                caption=&quot;{0}&quot;
        ///                :value.sync=&quot;privateRecord.{0}&quot;
        ///              &gt;&lt;/vnumber&gt;.
        /// </summary>
        internal static string CRUD4detailsVNumberINT {
            get {
                return ResourceManager.GetString("CRUD4detailsVNumberINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import general from &quot;@/general&quot;;
        ///
        ///class {0} {
        ///
        /////PHP PDO, always returns string for all dbase column types. So here user, must cast it, if he like it to use as for example on checkbox
        ///
        ///  constructor(data) {
        ///    
        ///    if (data != null) {
        ///{1}
        ///    }
        ///    else {
        ///{2}
        ///	//new Date().toISOString().substr(0, 10);
        ///    }
        ///  }
        ///
        ///}
        ///
        ///export default {0}.
        /// </summary>
        internal static string CRUD4entityJS {
            get {
                return ResourceManager.GetString("CRUD4entityJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;template&gt;
        ///  &lt;v-card&gt;
        ///    &lt;!-- &lt;v-card-title&gt;{0}&lt;/v-card-title&gt;  --&gt;
        ///    &lt;v-snackbar v-model=&quot;snackbar&quot; timeout=&quot;2500&quot;&gt;
        ///      {{snackbarMessage}}
        ///    &lt;/v-snackbar&gt;
        ///    &lt;v-card-title&gt;
        ///      &lt;v-btn elevation=&quot;1&quot; @click=&quot;show{0}Detail=true&quot;&gt;add new&lt;/v-btn&gt;
        ///      &lt;v-spacer&gt;&lt;/v-spacer&gt;
        ///      &lt;v-text-field
        ///        v-model=&quot;search&quot;
        ///        append-icon=&quot;mdi-magnify&quot;
        ///        @click:append=&quot;FillGrid{0}()&quot;
        ///        label=&quot;Search&quot;
        ///        single-line
        ///        hide-details
        ///        v-on:keyup.13=&quot;FillGrid{0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD4entityVUE {
            get {
                return ResourceManager.GetString("CRUD4entityVUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ////////////////////////////////// EXPAND FUNCTIONS //////////////////////////////////
        ///    async ApiChildFillGrid(item) {
        ///      let formData = new FormData();
        ///      formData.append(&quot;action&quot;, &quot;GetRecordDetails{0}&quot;);
        ///      formData.append(&quot;{4}&quot;, item.{1});
        ///
        ///      const items = await general.GetData(&quot;/api/{0}API.php&quot;, formData);
        ///           
        ///      if (!items || items.error) {
        ///        alert(&quot;Error in communication with the Server!&quot;);
        ///        return null;
        ///      }
        ///
        ///      return items;
        ///    },
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD4entityVUEexpandableCode {
            get {
                return ResourceManager.GetString("CRUD4entityVUEexpandableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;style scoped&gt;
        ///  /* Remove Box Shadow from Expandable - https://stackoverflow.com/questions/65699775/remove-box-shadow-from-expandable-data-table-in-vuetify */
        ///  .v-data-table &gt;&gt;&gt; .v-data-table__wrapper tbody tr.v-data-table__expanded__content {
        ///    box-shadow: none;
        ///  }
        ///&lt;/style&gt;
        ///
        ///.
        /// </summary>
        internal static string CRUD4entityVUEexpandableCSS {
            get {
                return ResourceManager.GetString("CRUD4entityVUEexpandableCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      single-expand 
        ///      show-expand
        ///    @item-expanded=&quot;loadDetails&quot;&gt;
        ///      &lt;!-- expanded --&gt;
        ///      &lt;template v-slot:expanded-item=&quot;{ headers, item }&quot;&gt;
        ///          &lt;td :colspan=&quot;headers.length&quot; style=&quot;padding:15px&quot;&gt;
        ///              &lt;v-simple-table dense&gt;
        ///                &lt;template v-slot:default&gt;
        ///                  &lt;thead&gt;
        ///                      &lt;tr&gt;
        ///{0}
        ///                      &lt;/tr&gt;
        ///                  &lt;/thead&gt;
        ///                  &lt;tbody&gt;
        ///                  &lt;tr v-for=&quot;rec in item.details&quot; :key=&quot;rec.du [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD4entityVUEexpandableElement {
            get {
                return ResourceManager.GetString("CRUD4entityVUEexpandableElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////*
        ///@session_start();
        ///
        ///if (!isset($_SESSION[&apos;id&apos;]) || empty($_POST[&apos;id&apos;])) {
        ///	echo json_encode(null);
        ///	exit ;
        ///}
        ///*/
        ///
        ///require_once &apos;general.php&apos;;
        ///
        ///if (!isset($_POST[&apos;action&apos;])){
        ///	ReportJS(1, &apos;No valid parameter!&apos;);
        ///	exit;
        ///}
        ///
        ///////////////////ACTIONS
        ///$action = $_POST[&apos;action&apos;];
        ///
        ///switch ($action) {
        ///	case &apos;FillGrid{0}&apos; :
        ///		FillGrid{0}();
        ///		break;
        ///	case &apos;GetRecord{0}&apos;:
        ///		GetRecord{0}();
        ///		break;	
        ///	case &apos;SaveRecord{0}&apos;:
        ///		SaveRecord{0}();
        ///		break;
        ///	case &apos;DeleteRecord{0}&apos;:
        ///		DeleteReco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD4phpAPI {
            get {
                return ResourceManager.GetString("CRUD4phpAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetRecords{0}(){
        ///
        ///    $db = new dbase();
        ///    $db-&gt;connect_mysql();
        ///
        ///    echo json_encode( $db-&gt;getSet(&apos;select {1},{2} from {0}&apos;, null));
        ///}
        ///.
        /// </summary>
        internal static string CRUD4phpGetRecodsFK {
            get {
                return ResourceManager.GetString("CRUD4phpGetRecodsFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	case &apos;GetRecords{0}&apos;:
        ///		GetRecords{0}();
        ///		break;
        ///.
        /// </summary>
        internal static string CRUD4phpGetRecodsFKcall {
            get {
                return ResourceManager.GetString("CRUD4phpGetRecodsFKcall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetRecordDetails{3}(){
        ///
        ///    $recID = $_POST[&apos;{0}&apos;];
        ///
        ///    $db = new dbase();
        ///    $db-&gt;connect_mysql();
        ///
        ///    echo json_encode($db-&gt;getSet(&quot;select {1} from {2} where {0}=?&quot;, array($recID)));
        ///}.
        /// </summary>
        internal static string CRUD4phpGetRecordDetails {
            get {
                return ResourceManager.GetString("CRUD4phpGetRecordDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	case &apos;GetRecordDetails{0}&apos;:
        ///		GetRecordDetails{0}();
        ///		break;.
        /// </summary>
        internal static string CRUD4phpGetRecordDetailsCall {
            get {
                return ResourceManager.GetString("CRUD4phpGetRecordDetailsCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {
        ///    path: &apos;/{0}&apos;,
        ///    name: &apos;{0}&apos;,
        ///    component: () =&gt;
        ///      import(/* webpackChunkName: &quot;bundle.{0}&quot; */ &apos;./components/{1}.vue&apos;),
        ///  },
        ///.
        /// </summary>
        internal static string CRUD4route {
            get {
                return ResourceManager.GetString("CRUD4route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Vue from &apos;vue&apos;;
        ///import VueRouter from &apos;vue-router&apos;;
        ///import pagenotfound from &apos;./components/page-not-found&apos;;
        ///
        ///Vue.use(VueRouter);
        ///
        ///const routes = [
        ///  {
        ///    path: &apos;/&apos;,
        ///    redirect: &apos;/{0}&apos;,
        ///  },
        ///{1}
        ///  {
        ///    path: &apos;*&apos;,
        ///    component: pagenotfound,
        ///  },
        ///]
        ///
        ///const router = new VueRouter({
        ///  mode: &apos;history&apos;,
        ///  base: process.env.VUE_APP_BASE_URL,
        ///  routes
        ///})
        ///
        ///export default router;.
        /// </summary>
        internal static string CRUD4routeTemplate {
            get {
                return ResourceManager.GetString("CRUD4routeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;template&gt;
        ///  &lt;v-card&gt;
        ///    &lt;v-tabs bg-color=&quot;primary&quot;&gt;
        ///{0}
        ///    &lt;/v-tabs&gt;
        ///  &lt;/v-card&gt;
        ///&lt;/template&gt;
        ///
        ///&lt;script&gt;
        ///export default {
        ///  data() {
        ///    return {
        ///      date: new Date().toLocaleString(),
        ///    };
        ///  },
        ///};
        ///&lt;/script&gt;
        ///.
        /// </summary>
        internal static string CRUD5appVueMain {
            get {
                return ResourceManager.GetString("CRUD5appVueMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;template&gt;
        ///  &lt;v-dialog v-model=&quot;showModal&quot; fullscreen&gt;
        ///    &lt;v-card&gt;
        ///      &lt;v-toolbar dark color=&quot;primary&quot;&gt;
        ///        &lt;v-btn icon dark @click=&quot;close()&quot;&gt;
        ///          &lt;v-icon&gt;mdi-close&lt;/v-icon&gt;
        ///        &lt;/v-btn&gt;
        ///        &lt;v-toolbar-title&gt;{{ header }}&lt;/v-toolbar-title&gt;
        ///        &lt;v-spacer&gt;&lt;/v-spacer&gt;
        ///        &lt;v-toolbar-items&gt;
        ///          &lt;v-btn
        ///            dark
        ///            text
        ///            v-if=&quot;privateRecord.{0} &gt; 0&quot;
        ///            @click=&quot;deleteRecord()&quot;
        ///          &gt;
        ///            Delete
        ///          &lt;/v-btn&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD5details {
            get {
                return ResourceManager.GetString("CRUD5details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               &lt;v-switch
        ///                v-model=&quot;privateRecord.{0}&quot;
        ///                color=&quot;primary&quot;
        ///                label=&quot;{0}&quot;
        ///              &gt;&lt;/v-switch&gt;.
        /// </summary>
        internal static string CRUD5detailsSwitchElement {
            get {
                return ResourceManager.GetString("CRUD5detailsSwitchElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import general from &quot;../general.js&quot;;
        ///
        ///class {0} {
        ///
        /////PHP PDO, always returns string for all dbase column types. So here user, must cast it, if he like it to use as for example on checkbox
        ///
        ///  constructor(data) {
        ///    
        ///    if (data != null) {
        ///{1}
        ///    }
        ///    else {
        ///{2}
        ///	//new Date().toISOString().substr(0, 10);
        ///    }
        ///  }
        ///
        ///}
        ///
        ///export default {0}.
        /// </summary>
        internal static string CRUD5entityJS {
            get {
                return ResourceManager.GetString("CRUD5entityJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;template&gt;
        ///  &lt;v-card&gt;
        ///    &lt;v-snackbar
        ///      :timeout=&quot;2500&quot;
        ///      color=&quot;blue-grey&quot;
        ///      rounded=&quot;pill&quot;
        ///      v-model=&quot;snackbar&quot;
        ///    &gt;
        ///      {{ snackbarMessage }}
        ///    &lt;/v-snackbar&gt;
        ///    &lt;v-card-title&gt;
        ///      &lt;v-row no-gutters&gt;
        ///        &lt;v-col class=&quot;item&quot; cols=&quot;12&quot; sm=&quot;6&quot; md=&quot;4&quot;&gt;
        ///          &lt;v-btn elevation=&quot;1&quot; @click=&quot;show{0}Detail = true&quot;
        ///            &gt;add new&lt;/v-btn
        ///          &gt;
        ///        &lt;/v-col&gt;
        ///        &lt;v-col class=&quot;item&quot; cols=&quot;12&quot; sm=&quot;6&quot; md=&quot;4&quot;&gt;
        ///          &lt;v-spacer&gt;&lt;/v-spacer&gt;
        ///          &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD5entityVUE {
            get {
                return ResourceManager.GetString("CRUD5entityVUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   { 
        ///    path: &apos;/{0}&apos;,
        ///    component: (() =&gt; vueImport(&apos;./components/{1}.vue&apos;)),
        ///  },.
        /// </summary>
        internal static string CRUD5route {
            get {
                return ResourceManager.GetString("CRUD5route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { createRouter, createWebHashHistory } from &apos;vue-router&apos;;
        ///import vueImport from &apos;vue-import&apos;;
        ///
        ///const routes = [
        ///  { path: &apos;/&apos;, redirect: &apos;/{0}&apos; },
        ///  /* dont use &apos;await vueImport&apos; as will load all the components on load!! */
        ///{1}
        ///  {
        ///    path: &apos;/:catchAll(.*)&apos;,
        ///    component: (() =&gt; vueImport(&apos;./components/page-not-found.vue&apos;)),
        ///  },
        ///];
        ///
        ///const router = createRouter({
        ///  history: createWebHashHistory(),
        ///  routes,
        ///});
        ///
        ///export default router;
        ///.
        /// </summary>
        internal static string CRUD5routeTemplate {
            get {
                return ResourceManager.GetString("CRUD5routeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///function connect() {
        ///	$mysql_hostname = &quot;localhost&quot;;  //your mysql host name
        ///	$mysql_user = &quot;&quot;;			//your mysql user name
        ///	$mysql_password = &quot;&quot;;			//your mysql password
        ///	$mysql_database = &quot;&quot;;	//your mysql database
        ///	
        ///	$dbh = new PDO(&quot;mysql:host=$mysql_hostname;dbname=$mysql_database&quot;, $mysql_user, $mysql_password);
        ///	
        ///	//enable utf8!
        ///	$dbh-&gt;exec(&quot;set names utf8&quot;);
        ///	
        ///	return $dbh;
        ///}
        ///
        ///?&gt;.
        /// </summary>
        internal static string CRUDtemplate_config_mysql {
            get {
                return ResourceManager.GetString("CRUDtemplate_config_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///function connect() {
        ///
        ///	$dbh = new PDO(&apos;sqlite:#filename#&apos;);
        ///	
        ///	/*
        ///	if (date(&apos;d&apos;)==15)
        ///	{	
        ///		$dbh-&gt;exec(&quot;VACUUM&quot;);
        ///		echo &quot;VACUUM done!&quot;;
        ///		exit;
        ///	}
        ///	*/
        ///		
        ///	//enable utf8!
        ///	$dbh-&gt;exec(&quot;set names utf8&quot;);
        ///	
        ///	return $dbh;
        ///}
        ///
        ///?&gt;.
        /// </summary>
        internal static string CRUDtemplate_config_sqlite {
            get {
                return ResourceManager.GetString("CRUDtemplate_config_sqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	//init datepicker
        ///	$(&apos;[name=*field*]&apos;).datepicker().on(&apos;changeDate&apos;, function(ev)
        ///	{
        ///		$(&apos;[name=*field*]&apos;).datepicker(&apos;hide&apos;); //close when selected
        ///	});
        ///
        ///	var d1 = new Date();
        ///	d1.setDate(d1.getDate());
        ///		
        ///	//set default value
        ///	$(&apos;[name=*field*]&apos;).datepicker(&apos;setValue&apos;, d1)
        ///.
        /// </summary>
        internal static string CRUDtemplate_Control_DTP_init {
            get {
                return ResourceManager.GetString("CRUDtemplate_Control_DTP_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    $(&apos;[name=*field*]&apos;).datetimepicker({
        ///        weekStart: 1,
        ///        todayBtn:  1,
        ///		autoclose: 1,
        ///		todayHighlight: 1,
        ///		startView: 2,
        ///		minView: 2,
        ///		forceParse: 1
        ///    });
        ///	
        ///	//set default value
        ///	$(&apos;[name=*field*]&apos;).val(new Date().toISOString().slice(0, 10));
        ///.
        /// </summary>
        internal static string CRUDtemplate_Control_DTPmalot {
            get {
                return ResourceManager.GetString("CRUDtemplate_Control_DTPmalot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    $(&apos;[name=*field*]&apos;).datetimepicker({
        ///        weekStart: 1,
        ///        todayBtn:  1,
        ///		autoclose: 1,
        ///		todayHighlight: 1,
        ///		startView: 2,
        ///		forceParse: 1
        ///    });
        ///	
        ///	//set default value
        ///	$(&apos;[name=*field*]&apos;).val(new Date().toISOString().slice(0, 10) + &quot; 00:00&quot;);
        ///.
        /// </summary>
        internal static string CRUDtemplate_Control_DTPtime_init {
            get {
                return ResourceManager.GetString("CRUDtemplate_Control_DTPtime_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////	header(&quot;Location: index.html&quot;);
        /////	exit ;
        /////}
        ///
        ///if (!isset($_GET[&apos;id&apos;])) {
        ///	echo &quot;error010101010&quot;;
        ///	return;
        ///}
        ///
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db = connect();
        ///
        ///$sql = &quot;DELETE FROM `#table#` WHERE #PK#=:#PK#&quot;;
        ///$sth = $db-&gt;prepare($sql);
        ///$sth-&gt;bindValue(&apos;:#PK#&apos;, $_GET[&apos;id&apos;]);
        ///	
        ///$sth-&gt;execute();
        ///
        ///$g = $sth-&gt;rowCount();
        ///
        ///if($g == 1)
        ///	header(&quot;Location: tab_#table#.php?isdelete=1&quot;);
        ///else
        ///	header(&quot;Location: tab_#table#.php?i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_delete {
            get {
                return ResourceManager.GetString("CRUDtemplate_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////	header(&quot;Location: index.html&quot;);
        /////	exit ;
        /////}
        ///
        ///$active_tab=&quot;#table#&quot;;
        ///
        ///require_once (&apos;template_top.php&apos;);
        ///
        ///// include DB
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db       = connect();
        ///
        ///#FKs#
        ///
        ///$row=null;
        //////////////////////READ SPEFIC RECORD
        ///if (isset($_GET[&quot;id&quot;])) {
        ///	$find_sql = &quot;SELECT * FROM `#table#` where #PK# = :id&quot;;
        ///
        ///	$stmt      = $db-&gt;prepare($find_sql);
        ///	$stmt-&gt;bindValue(&apos;:id&apos;, $_GET[&quot;id&quot;]);
        ///	
        ///	$stmt-&gt;execute();
        ///	$row = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_detail {
            get {
                return ResourceManager.GetString("CRUDtemplate_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$#table#_rows=null;
        //////////////////////READ #table#
        ///	$find_sql = &quot;SELECT * FROM `#table#` order by #txt#&quot;;
        ///	$stmt      = $db-&gt;prepare($find_sql);
        ///	
        ///	$stmt-&gt;execute();
        ///	$#table#_rows = $stmt-&gt;fetchAll();
        //////////////////////READ #table#
        ///
        ///.
        /// </summary>
        internal static string CRUDtemplate_FK_Control_FILL {
            get {
                return ResourceManager.GetString("CRUDtemplate_FK_Control_FILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	///////////////////////////////////////////////////////////// FILL #table#
        ///	var jArray_#table# =   &lt;?php echo json_encode($#table#_rows); ?&gt;;
        ///
        ///	var combo_#table#_rows = &quot;&lt;option value=&apos;0&apos;&gt;&lt;/option&gt;&quot;;
        ///	for (var i = 0; i &lt; jArray_#table#.length; i++)
        ///	{
        ///		combo_#table#_rows += &quot;&lt;option value=&apos;&quot; + jArray_#table#[i][&quot;#PK#&quot;] + &quot;&apos;&gt;&quot; + jArray_#table#[i][&quot;#TXT#&quot;] + &quot;&lt;/option&gt;&quot;;
        ///	}
        ///
        ///	$(&quot;[name=#FK_NAME#]&quot;).html(combo_#table#_rows);
        ///	$(&quot;[name=#FK_NAME#]&quot;).change(); //select row 0 - no conflict on POST val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_FK_Control_FILL_COMBO {
            get {
                return ResourceManager.GetString("CRUDtemplate_FK_Control_FILL_COMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////	header(&quot;Location: index.html&quot;);
        /////	exit ;
        /////}
        ///
        ///$active_tab = &quot;#tblname#&quot;;
        ///
        ///if(#validation#){
        ///	echo &quot;error010101010&quot;;
        ///	return;
        ///}
        ///
        ///// include DB
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db = connect();
        ///
        ///#checkboxes#
        ///
        ///#dtptimes#
        ///
        ///$ret_val=&quot;&quot;;
        ///if(isset($_POST[&apos;#tblname#FORM_updateID&apos;]) &amp;&amp; !empty($_POST[&apos;#tblname#FORM_updateID&apos;]))
        ///{
        ///	$sql = &quot;UPDATE `#tblname#` set #updateVAL# WHERE #updateWhere#=:#updateWhere#&quot;;
        ///	$stmt = $db-&gt;prepar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_save {
            get {
                return ResourceManager.GetString("CRUDtemplate_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$*field* = *0var*;
        ///
        ///if (isset($_POST[&apos;*field*&apos;])) {
        ///	if ($_POST[&apos;*field*&apos;] == &quot;on&quot;)
        ///		$*field* = 1;
        ///	else
        ///		$*field* = *0var*;
        ///}
        ///.
        /// </summary>
        internal static string CRUDtemplate_save_checkbox_validation {
            get {
                return ResourceManager.GetString("CRUDtemplate_save_checkbox_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$*field*=null;
        ///if (!empty($_POST[&apos;*field*&apos;]))
        ///{
        ///	$dt = DateTime::createFromFormat(&apos;d-m-Y&apos;, $_POST[&apos;*field*&apos;]);
        ///	
        ///	$*field* =	$dt-&gt;format(&apos;Y-m-d&apos;);
        ///}
        ///.
        /// </summary>
        internal static string CRUDtemplate_save_dtpmalot_validation {
            get {
                return ResourceManager.GetString("CRUDtemplate_save_dtpmalot_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$*field*=null;
        ///if (!empty($_POST[&apos;*field*&apos;]))
        ///{
        ///	$dt = DateTime::createFromFormat(&apos;d-m-Y H:i&apos;, $_POST[&apos;*field*&apos;]);
        ///	
        ///	$*field* =	$dt-&gt;format(&apos;Y-m-d H:i:s&apos;);
        ///}
        ///.
        /// </summary>
        internal static string CRUDtemplate_save_dtptime_validation {
            get {
                return ResourceManager.GetString("CRUDtemplate_save_dtptime_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////	header(&quot;Location: index.html&quot;);
        /////	exit ;
        /////}
        ///
        ///$active_tab=&quot;#table#&quot;;
        ///
        ///require_once (&apos;template_top.php&apos;);
        ///
        ///// include DB
        ///require_once (&apos;config.php&apos;);
        ///
        ///$table_columns_caps = array(
        ///#fields#
        ///);
        ///
        ///$table_columns = array(
        ///#fields#
        ///);
        ///
        ///$db       = connect();
        ///
        ///$find_sql = &quot;SELECT #select# FROM `#table#`#joins#&quot;;
        ///
        ///$stmt      = $db-&gt;prepare($find_sql);
        ///$stmt-&gt;execute();
        ///$rows_sql = $stmt-&gt;fetchAll();
        ///$rows= array();
        ///
        ///forea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_table {
            get {
                return ResourceManager.GetString("CRUDtemplate_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///	&lt;!--http://glyphicons.bootstrapcheatsheets.com/--&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;title&gt;AdminLTE | Dashboard&lt;/title&gt;
        ///		&lt;meta content=&apos;width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no&apos; name=&apos;viewport&apos;&gt;
        ///		&lt;!-- bootstrap 3.0.2 --&gt;
        ///		&lt;link href=&quot;css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///		&lt;!-- Theme style --&gt;
        ///		&lt;link href=&quot;css/AdminLTE.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///		&lt;!-- Datatables style --&gt;
        ///		&lt;link href=&quot;css/datatables/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_top {
            get {
                return ResourceManager.GetString("CRUDtemplate_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 						&lt;li class=&quot;treeview &lt;?php if (isset($active_tab) &amp;&amp; $active_tab==&quot;#table#&quot;) echo &quot;active&quot;?&gt; &quot;&gt;
        ///							&lt;a href=&quot;#&quot;&gt; &lt;i class=&quot;glyphicon glyphicon-th-large&quot;&gt;&lt;/i&gt; &lt;span&gt;#table#&lt;/span&gt; &lt;i class=&quot;glyphicon pull-right glyphicon-chevron-right&quot;&gt;&lt;/i&gt; &lt;/a&gt;
        ///							&lt;ul class=&quot;treeview-menu&quot; style=&quot;display: none;&quot;&gt;
        ///								&lt;li &gt;
        ///									&lt;a href=&quot;tab_#table#.php&quot; style=&quot;margin-left: 10px;&quot;&gt;&lt;i class=&quot;glyphicon glyphicon-list&quot;&gt;&lt;/i&gt; List&lt;/a&gt;
        ///								&lt;/li&gt;
        ///								&lt;li &gt;
        ///									&lt;a href=&quot;tab_#table#_details.php [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_top_item {
            get {
                return ResourceManager.GetString("CRUDtemplate_top_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document {
            get {
                object obj = ResourceManager.GetObject("document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_new {
            get {
                object obj = ResourceManager.GetObject("document_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export16 {
            get {
                object obj = ResourceManager.GetObject("export16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap helpEXCEL {
            get {
                object obj = ResourceManager.GetObject("helpEXCEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///if (**post validation**) {
        ///	echo &quot;error010101010&quot;;
        ///	return;
        ///}
        ///
        ///**bit validation**
        ///
        ///require_once (&apos;general.php&apos;);
        ///
        ///$db = connect();
        ///
        ///if ($stmt = $db -&gt; prepare(&quot;call **proc_name** (**q**)&quot;)) {
        ///
        ///	//bind our params
        ///	$stmt -&gt; bind_param(&apos;**s**&apos;, **bind_param**);
        ///	
        ///**bind_set**
        ///
        ///		/* Execute the prepared Statement */
        ///		$stmt -&gt; execute();
        ///
        ///		$g = $stmt -&gt; affected_rows;
        ///
        ///		if ($g == -1)
        ///			echo &quot;error&quot;;
        ///		else
        ///			echo &quot;ok&quot;;
        ///}
        ///
        /////close the statement
        ///$stmt -&gt; close();
        ///
        ///$db  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mySQLtunnelPHPproc_save {
            get {
                return ResourceManager.GetString("mySQLtunnelPHPproc_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nodeJS {
            get {
                object obj = ResourceManager.GetObject("nodeJS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if(#validation#){
        ///	header($_SERVER[&apos;SERVER_PROTOCOL&apos;] . &apos; 500 Internal Server Error&apos;, true, 500);
        ///	exit;
        ///}
        ///
        ///$db = connect();
        ///
        ///if(isset($_POST[&apos;#tblname#FORM_updateID&apos;]) &amp;&amp; !empty($_POST[&apos;#tblname#FORM_updateID&apos;]))
        ///{
        ///	$sql = &apos;UPDATE `#tblname#` set #updateVAL# WHERE #updateWhere#=:#updateWhere#&apos;;
        ///	$stmt = $db-&gt;prepare($sql);
        ///	$stmt-&gt;bindValue(&apos;:#updateWhere#&apos;, $_POST[&apos;#tblname#FORM_updateID&apos;]);
        ///}
        ///else
        ///{
        ///	$sql = &apos;INSERT INTO `#tblname#` (#insertFields#) VALUES (#insertVAL#)&apos;;
        ///	$stmt = $db-&gt;pre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PDOprepared {
            get {
                return ResourceManager.GetString("PDOprepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			&lt;li&gt;
        ///				&lt;a href=&quot;##table#TAB&quot; data-toggle=&apos;tab&apos;&gt;#table#&lt;/a&gt;
        ///			&lt;/li&gt;
        ///
        ///
        ///			&lt;div class=&quot;tab-pane fade&quot; id=&quot;#table#TAB&quot;&gt;
        ///				&lt;div id=&quot;#table#&quot;&gt;
        ///					&lt;?php
        ///					include (&apos;tab_#table#.php&apos;);
        ///					?&gt;
        ///				&lt;/div&gt;
        ///				&lt;div id=&quot;#table#_details&quot;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;.
        /// </summary>
        internal static string PHPpagesPORTAL {
            get {
                return ResourceManager.GetString("PHPpagesPORTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///session_start();
        ///
        ///if (!isset($_SESSION[&quot;u&quot;])) {
        ///	header(&quot;Location: index.html&quot;);
        ///	exit ;
        ///}
        ///?&gt;
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Portal&lt;/title&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///
        ///		&lt;link href=&quot;css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        /// 
        ///		&lt;script type=&apos;text/javascript&apos; src=&quot;js/jquery-1.10.2.min.js&quot;&gt;&lt;/script&gt;
        ///		&lt;script type=&apos;text/javascript&apos; src=&quot;js/bootstrap.min.js&quot;&gt;&lt;/sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesPORTALexample {
            get {
                return ResourceManager.GetString("PHPpagesPORTALexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///session_start();
        ///
        ///if (!isset($_SESSION[&quot;u&quot;])) {
        ///    header(&quot;Location: index.html&quot;);
        ///    exit ;
        ///}
        ///
        ///if (!isset($_POST[&apos;category_id&apos;])) {
        ///	echo &quot;error010101010&quot;;
        ///	return;
        ///}
        ///
        ///require_once (&apos;92nNE1WK_config.php&apos;);
        ///
        ///$db = connect();
        ///
        ///if ($stmt = $db -&gt; prepare(&quot;call categories_delete (?)&quot;)) {
        ///
        ///	//bind param
        ///	$stmt -&gt; bind_param(&apos;s&apos;, $rec_id);
        ///	
        ///	$rec_id=$_POST[&apos;category_id&apos;];
        ///	
        ///	/* Execute the prepared Statement */
        ///	$stmt -&gt; execute();
        ///
        ///	$g = $stmt -&gt; affected_rows;
        ///
        ///	if ($g = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesPORTALprocedureDELETE_callexample {
            get {
                return ResourceManager.GetString("PHPpagesPORTALprocedureDELETE_callexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///
        ///if (!isset($_POST[&apos;comp_title&apos;]) || !isset($_POST[&apos;comp_name&apos;]) || !isset($_POST[&apos;cmp_password&apos;]) || !isset($_POST[&apos;page_editor&apos;]) || !isset($_POST[&apos;admin_name&apos;]) || !isset($_POST[&apos;comp_address&apos;]) || !isset($_POST[&apos;zipcode&apos;]) || !isset($_POST[&apos;area&apos;]) || !isset($_POST[&apos;phone_old&apos;]) || !isset($_POST[&apos;fax&apos;]) || !isset($_POST[&apos;email&apos;]) || !isset($_POST[&apos;url&apos;]) || !isset($_POST[&apos;member_group&apos;]) || !isset($_POST[&apos;member_international&apos;]) || !isset($_POST[&apos;member_syndicate&apos;]) || !isset($_POST[&apos;media_uni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesPORTALprocedureSAVE_callexample {
            get {
                return ResourceManager.GetString("PHPpagesPORTALprocedureSAVE_callexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE `bestof_save` (
        ///	IN `rec_idVAR` INT
        ///	,IN `customer_idVAR` INT
        ///	,IN `company_idVAR` INT
        ///	,IN `titleVAR` VARCHAR(250) CHARSET utf8
        ///	,IN `productVAR` VARCHAR(250) CHARSET utf8
        ///	,IN `infosVAR` VARCHAR(2000) CHARSET utf8
        ///	,IN `vimeoVAR` VARCHAR(250) CHARSET utf8
        ///	,IN `pictureVAR` VARCHAR(250) CHARSET utf8
        ///	,IN `categoryVAR` VARCHAR(250) CHARSET utf8
        ///	,IN `soundcloudVAR` VARCHAR(250) CHARSET utf8
        ///	,IN `flickrVAR` VARCHAR(250) CHARSET utf8
        ///	,IN `lastupdateVAR` DATETIME
        ///	)
        ///
        ///BEGIN
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesPORTALprocedureSAVEexample {
            get {
                return ResourceManager.GetString("PHPpagesPORTALprocedureSAVEexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///session_start();
        ///
        ///if (!isset($_SESSION[&quot;u&quot;])) {
        ///	header(&quot;Location: index.html&quot;);
        ///	exit ;
        ///}
        ///?&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///	var last_**table**_Page;
        ///
        ///	function load_**table**_Records(page) {
        ///
        ///		$(&quot;#loading&quot;).height($(&apos;body&apos;).height());
        ///		$(&quot;#loading&quot;).show();
        ///
        ///		last_**table**_Page = page;
        ///
        ///		$.ajax({
        ///			type : &quot;GET&quot;,
        ///			url : &quot;tab_**table**_pagination.php&quot;,
        ///			data : {
        ///				page : page,
        ///				where : $(&quot;#**table**_search_combo&quot;).val(),
        ///				where_val : $(&quot;#**table**_search_tx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesSELECT {
            get {
                return ResourceManager.GetString("PHPpagesSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///session_start();
        ///
        ///if (!isset($_SESSION[&quot;u&quot;])) {
        ///	header(&quot;Location: index.html&quot;);
        ///	exit ;
        ///}
        ///
        ///include (config.php&apos;);
        ///
        ///$conn = connect();
        ///
        //////////////////////READ CATEGORIES
        ///// $stmt = $conn -&gt; prepare(&apos;select categ_id,categ_path from categories order by categ_path&apos;);
        ///// 
        ///// $stmt -&gt; execute();
        /////
        ///// //when get_result() is not available use :
        ///// //$stmt-&gt;bind_result($f1,$f2);  
        /////
        ///// $result = $stmt -&gt; get_result();
        ///// $categories;
        ///// $x = 0;
        ///// 
        ///// while ($row = $result -&gt; fetch_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesSELECTdetail {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;
        ///					&lt;input name=&apos;*field*&apos; class=&apos;form-control&apos; maxlength=&quot;*fieldsize*&quot; placeholder=&apos;*field*&apos;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;&lt;br&gt;
        ///					&lt;input type=&quot;checkbox&quot; name=&apos;*field*&apos;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_CHECK {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;
        ///					&lt;select id=&quot;*field*&quot; name=&apos;*field*&apos; class=&apos;form-control&apos;&gt;
        ///					&lt;/select&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_COMBO {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_COMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;&lt;br&gt;
        ///					&lt;input type=&quot;text&quot; class=&quot;form-control&quot; name=&quot;*field*&quot; data-date-format=&quot;yyyy-mm-dd&quot; style=&quot;width:100px&quot; &gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_DTP {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_DTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;&lt;br&gt;
        ///					&lt;input type=&quot;text&quot; name=&quot;*field*&quot; class=&quot;form-control&quot; data-date-format=&quot;dd-mm-yyyy&quot; readonly class=&quot;form_datetime&quot;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_DTPmalot {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_DTPmalot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;&lt;br&gt;
        ///					&lt;input type=&quot;text&quot; name=&quot;*field*&quot; class=&quot;form-control&quot; data-date-format=&quot;dd-mm-yyyy hh:ii&quot; readonly class=&quot;form_datetime&quot;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_DTPtime {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_DTPtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///session_start();
        ///
        ///if (!isset($_SESSION[&quot;u&quot;])) {
        ///    header(&quot;Location: index.html&quot;);
        ///    exit ;
        ///}
        ///
        ///// include your code to connect to DB.
        ///include (config.php&apos;);
        ///
        ///$conn = connect();
        ///
        /////your table name
        ///$tbl_name = &quot;**table**&quot;;
        ///
        ///// How many adjacent pages should be shown on each side?
        ///$adjacents = 3;
        ///
        ////*
        /// First get total number of rows in data table.
        /// If you have a WHERE clause in your query, make sure you mirror it here.
        /// */
        /// 
        ///$where = &quot;&quot;;
        ///if (isset($_GET[&apos;where&apos;]) &amp;&amp; isset($_GET [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesSELECTpagination {
            get {
                return ResourceManager.GetString("PHPpagesSELECTpagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHPtemplate {
            get {
                object obj = ResourceManager.GetObject("PHPtemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHPtemplateAPIbootstraptable {
            get {
                object obj = ResourceManager.GetObject("PHPtemplateAPIbootstraptable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHPtemplateCRUD {
            get {
                object obj = ResourceManager.GetObject("PHPtemplateCRUD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHPtemplateCRUDbootstraptable {
            get {
                object obj = ResourceManager.GetObject("PHPtemplateCRUDbootstraptable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHPtemplateVue2 {
            get {
                object obj = ResourceManager.GetObject("PHPtemplateVue2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHPtemplateVue3 {
            get {
                object obj = ResourceManager.GetObject("PHPtemplateVue3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh24 {
            get {
                object obj = ResourceManager.GetObject("refresh24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templateCRUDadminLTE {
            get {
                object obj = ResourceManager.GetObject("templateCRUDadminLTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templateCRUDbootstraptable {
            get {
                object obj = ResourceManager.GetObject("templateCRUDbootstraptable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templateCRUDbootstraptable5 {
            get {
                object obj = ResourceManager.GetObject("templateCRUDbootstraptable5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templateCRUDvue2 {
            get {
                object obj = ResourceManager.GetObject("templateCRUDvue2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templateCRUDvue3 {
            get {
                object obj = ResourceManager.GetObject("templateCRUDvue3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_marked {
            get {
                object obj = ResourceManager.GetObject("text_marked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///if (!isset($_POST[&quot;sql&quot;]) || !isset($_POST[&quot;p&quot;])) {
        ///	// if(!isset($_POST[&quot;sql&quot;]) || !isset($_POST[&quot;p&quot;])){
        ///	echo json_encode(&quot;Error: no token1&quot;);
        ///	return;
        ///	// }
        ///} else if ($_POST[&quot;p&quot;] != **password entered at desktop program**) {
        ///	echo json_encode(&quot;Error: no token2&quot;);
        ///	return;
        ///}
        ///
        ///$x = json_decode($_POST[&quot;sql&quot;]);
        ///
        ////////////////////////////////////////////////////////////////////////////////////////
        ///// 			SETUP MYSQL CONNECTION [START]
        ///////////////////////////////////////////////////////// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tunnelPHP {
            get {
                return ResourceManager.GetString("tunnelPHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///if (!isset($_POST[&quot;sql&quot;]) || !isset($_POST[&quot;p&quot;])) {
        ///	echo json_encode(&quot;Error: no token1&quot;);
        ///	return;
        ///} else if ($_POST[&quot;p&quot;] != **password entered at desktop program**) {
        ///	echo json_encode(&quot;Error: no token2&quot;);
        ///	return;
        ///}
        ///
        ///try {
        ///	//on old server something wrong with json_decode, use also the same function &apos;_json_decode&apos;, on transfer batch functions
        ///	$x = _json_decode($_POST[&quot;sql&quot;]);
        ///
        ///	/////////////////////////////////////////////////////////////////////////////////////
        ///	// 			SETUP MYSQL CO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tunnelPHP_PDO {
            get {
                return ResourceManager.GetString("tunnelPHP_PDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///if (!isset($_POST[&quot;sql&quot;]) || !isset($_POST[&quot;p&quot;])) {
        ///	echo json_encode(&quot;Error: no token1&quot;);
        ///	return;
        ///} else if ($_POST[&quot;p&quot;] != **password entered at desktop program**) {
        ///	echo json_encode(&quot;Error: no token2&quot;);
        ///	return;
        ///}
        ///
        ///try {
        ///	//on old server something wrong with json_decode, use also the same function &apos;_json_decode&apos;, on transfer batch functions
        ///	$x = _json_decode($_POST[&quot;sql&quot;]);
        ///
        ///	/////////////////////////////////////////////////////////////////////////////////////
        ///	// 			SETUP SQLSERVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tunnelPHP_PDO_SQLServer {
            get {
                return ResourceManager.GetString("tunnelPHP_PDO_SQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////add it near connect tunnel PHP file with name trans.php
        ///if(!isset($_POST[&apos;statement&apos;]))
        ///{		echo json_encode(&quot;error - no token1&quot;);
        ///		return;}
        ///
        ///if(!isset($_POST[&apos;record&apos;]))
        ///{		echo json_encode(&quot;error - no token2&quot;);
        ///		return;
        ///} else if ($_POST[&quot;p&quot;] != **password entered at desktop program**) {
        ///	echo json_encode(&quot;error - wrong password&quot;);
        ///	return;
        ///}
        ///
        ///$json = json_decode($_POST[&apos;statement&apos;]);
        ///$statement = $json -&gt; q;
        ///
        ///
        ///$json = json_decode($_POST[&apos;record&apos;],TRUE);
        ///
        ///
        ///$params=array();
        ///$ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tunnelPHPtrans {
            get {
                return ResourceManager.GetString("tunnelPHPtrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////add it near connect tunnel PHP file with name trans_batch.php
        ///
        ///if (!isset($_POST[&apos;statement&apos;])) {		echo json_encode(&quot;error - no token1&quot;);
        ///	return;
        ///}
        ///
        ///if (!isset($_POST[&apos;records&apos;])) {		echo json_encode(&quot;error - no token2&quot;);
        ///	return;
        ///} else if ($_POST[&quot;p&quot;] != **password entered at desktop program**) {
        ///	echo json_encode(&quot;error - wrong password&quot;);
        ///	return;
        ///}
        ///
        ///$json = json_decode($_POST[&apos;statement&apos;]);
        ///$statement = $json -&gt; q;
        ///
        ///$json = json_decode($_POST[&apos;records&apos;], TRUE);
        ///
        /////////////// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tunnelPHPtransBATCH {
            get {
                return ResourceManager.GetString("tunnelPHPtransBATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window {
            get {
                object obj = ResourceManager.GetObject("window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows {
            get {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
