//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about_logo {
            get {
                object obj = ResourceManager.GetObject("about-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Delete_icon {
            get {
                object obj = ResourceManager.GetObject("Button-Delete-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Delete_iconOther {
            get {
                object obj = ResourceManager.GetObject("Button-Delete-iconOther", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy16 {
            get {
                object obj = ResourceManager.GetObject("copy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;]) || empty($_POST[&apos;*PK*&apos;])) {
        /////    echo json_encode(null);
        /////    exit ;
        /////}
        ///
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db = connect();
        ///
        ///$sql = &quot;DELETE FROM `*table*` WHERE *PK*=:*PK*&quot;;
        ///$sth = $db-&gt;prepare($sql);
        ///$sth-&gt;bindValue(&apos;:*PK*&apos;, $_POST[&apos;*PK*&apos;]);
        ///	
        ///$sth-&gt;execute();
        ///
        ///echo $sth-&gt;errorCode(); 
        ///?&gt;.
        /// </summary>
        internal static string CRUD2template_delete {
            get {
                return ResourceManager.GetString("CRUD2template_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;]) || empty($_POST[&apos;*PK*&apos;])) {
        /////    echo json_encode(null);
        /////    exit ;
        /////}
        ///
        ///try {
        ///	include (&apos;config.php&apos;);
        ///
        ///	$db = connect();
        ///
        ///	$r= getRow($db, &quot;SELECT *select* FROM *table* where *PK*=?&quot;, array($_POST[&apos;*PK*&apos;]));
        ///
        ///    //unicode
        ///    header(&quot;Content-Type: application/json&quot;, true);
        ///	echo json_encode($r);
        ///
        ///	
        ///} catch (exception $e) {
        ///    echo json_encode(null);
        ///}
        ///?&gt;.
        /// </summary>
        internal static string CRUD2template_fetch {
            get {
                return ResourceManager.GetString("CRUD2template_fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////	header(&quot;Location: index.html&quot;);
        /////	exit ;
        /////}
        ///
        ///// include DB
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db       = connect();
        ///
        ///#FKs#
        ///?&gt;
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///		&lt;title&gt;
        ///			Bootstrap Table
        ///		&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;css/bootstrap.mi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD2template_main {
            get {
                return ResourceManager.GetString("CRUD2template_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///						&lt;th data-field=&quot;*field*&quot; data-visible=&quot;*fieldv*&quot;&gt;
        ///							*field*
        ///						&lt;/th&gt;
        ///						.
        /// </summary>
        internal static string CRUD2template_main_TABLE_Item {
            get {
                return ResourceManager.GetString("CRUD2template_main_TABLE_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////    header(&quot;Location: index.html&quot;);
        /////    exit ;
        /////}
        ///
        ///
        ///// include your code to connect to DB.
        ///include (&apos;config.php&apos;);
        ///
        ///$table_columns = array(
        ///#cols#
        ///);
        ///
        ///$conn     = connect();
        ///
        ///if (!is_numeric($_GET[&quot;limit&quot;]) || !is_numeric($_GET[&quot;offset&quot;]))
        ///{
        ///	echo &quot;error&quot;;
        ///	exit;
        ///}
        ///
        ///$limit = $_GET[&quot;limit&quot;];
        ///$offset= $_GET[&quot;offset&quot;];
        ///
        ///
        ///$sql=&quot;select #select_cols# from #table# #joins#&quot;;
        ///$count_query_sql = &quot;select count(*) from #table# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD2template_pagination {
            get {
                return ResourceManager.GetString("CRUD2template_pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////    echo json_encode(null);
        /////    exit ;
        /////}
        /// 
        ///if (#validation#){
        ///	echo &quot;error010101010&quot;;
        ///	return;
        ///}
        /// 
        /////DB
        ///require_once (&apos;config.php&apos;);
        /// 
        ///$db = connect();
        /// 
        ///#checkboxes#
        ///
        ///#dtptimes#
        ///
        ///if(isset($_POST[&apos;#tblname#FORM_updateID&apos;]) &amp;&amp; !empty($_POST[&apos;#tblname#FORM_updateID&apos;]))
        ///{
        ///	$sql = &quot;UPDATE #tblname# set #updateVAL# where #updateWhere#=:#updateWhere#&quot;;
        ///	$stmt = $db-&gt;prepare($sql);
        ///	$stmt-&gt;bindValue(&apos;:#updateWhere#&apos; , $_POS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUD2template_save {
            get {
                return ResourceManager.GetString("CRUD2template_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///function connect() {
        ///	$mysql_hostname = &quot;localhost&quot;;  //your mysql host name
        ///	$mysql_user = &quot;&quot;;			//your mysql user name
        ///	$mysql_password = &quot;&quot;;			//your mysql password
        ///	$mysql_database = &quot;&quot;;	//your mysql database
        ///	
        ///	$dbh = new PDO(&quot;mysql:host=$mysql_hostname;dbname=$mysql_database&quot;, $mysql_user, $mysql_password);
        ///	
        ///	//enable utf8!
        ///	$dbh-&gt;exec(&quot;set names utf8&quot;);
        ///	
        ///	return $dbh;
        ///}
        ///
        ///?&gt;.
        /// </summary>
        internal static string CRUDtemplate_config_mysql {
            get {
                return ResourceManager.GetString("CRUDtemplate_config_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///function connect() {
        ///
        ///	$dbh = new PDO(&apos;sqlite:#filename#&apos;);
        ///	
        ///	/*
        ///	if (date(&apos;d&apos;)==15)
        ///	{	
        ///		$dbh-&gt;exec(&quot;VACUUM&quot;);
        ///		echo &quot;VACUUM done!&quot;;
        ///		exit;
        ///	}
        ///	*/
        ///		
        ///	//enable utf8!
        ///	$dbh-&gt;exec(&quot;set names utf8&quot;);
        ///	
        ///	return $dbh;
        ///}
        ///
        ///?&gt;.
        /// </summary>
        internal static string CRUDtemplate_config_sqlite {
            get {
                return ResourceManager.GetString("CRUDtemplate_config_sqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	//init datepicker
        ///	$(&apos;[name=*field*]&apos;).datepicker().on(&apos;changeDate&apos;, function(ev)
        ///	{
        ///		$(&apos;[name=*field*]&apos;).datepicker(&apos;hide&apos;); //close when selected
        ///	});
        ///
        ///	var d1 = new Date();
        ///	d1.setDate(d1.getDate());
        ///		
        ///	//set default value
        ///	$(&apos;[name=*field*]&apos;).datepicker(&apos;setValue&apos;, d1)
        ///.
        /// </summary>
        internal static string CRUDtemplate_Control_DTP_init {
            get {
                return ResourceManager.GetString("CRUDtemplate_Control_DTP_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    $(&apos;[name=*field*]&apos;).datetimepicker({
        ///        weekStart: 1,
        ///        todayBtn:  1,
        ///		autoclose: 1,
        ///		todayHighlight: 1,
        ///		startView: 2,
        ///		minView: 2,
        ///		forceParse: 1
        ///    });
        ///	
        ///	//set default value
        ///	$(&apos;[name=*field*]&apos;).val(new Date().toISOString().slice(0, 10));
        ///.
        /// </summary>
        internal static string CRUDtemplate_Control_DTPmalot {
            get {
                return ResourceManager.GetString("CRUDtemplate_Control_DTPmalot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    $(&apos;[name=*field*]&apos;).datetimepicker({
        ///        weekStart: 1,
        ///        todayBtn:  1,
        ///		autoclose: 1,
        ///		todayHighlight: 1,
        ///		startView: 2,
        ///		forceParse: 1
        ///    });
        ///	
        ///	//set default value
        ///	$(&apos;[name=*field*]&apos;).val(new Date().toISOString().slice(0, 10) + &quot; 00:00&quot;);
        ///.
        /// </summary>
        internal static string CRUDtemplate_Control_DTPtime_init {
            get {
                return ResourceManager.GetString("CRUDtemplate_Control_DTPtime_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////	header(&quot;Location: index.html&quot;);
        /////	exit ;
        /////}
        ///
        ///if (!isset($_GET[&apos;id&apos;])) {
        ///	echo &quot;error010101010&quot;;
        ///	return;
        ///}
        ///
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db = connect();
        ///
        ///$sql = &quot;DELETE FROM `#table#` WHERE #PK#=:#PK#&quot;;
        ///$sth = $db-&gt;prepare($sql);
        ///$sth-&gt;bindValue(&apos;:#PK#&apos;, $_GET[&apos;id&apos;]);
        ///	
        ///$sth-&gt;execute();
        ///
        ///$g = $sth-&gt;rowCount();
        ///
        ///if($g == 1)
        ///	header(&quot;Location: tab_#table#.php?isdelete=1&quot;);
        ///else
        ///	header(&quot;Location: tab_#table#.php?i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_delete {
            get {
                return ResourceManager.GetString("CRUDtemplate_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////	header(&quot;Location: index.html&quot;);
        /////	exit ;
        /////}
        ///
        ///$active_tab=&quot;#table#&quot;;
        ///
        ///require_once (&apos;template_top.php&apos;);
        ///
        ///// include DB
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db       = connect();
        ///
        ///#FKs#
        ///
        ///$row=null;
        //////////////////////READ SPEFIC RECORD
        ///if (isset($_GET[&quot;id&quot;])) {
        ///	$find_sql = &quot;SELECT * FROM `#table#` where #PK# = :id&quot;;
        ///
        ///	$stmt      = $db-&gt;prepare($find_sql);
        ///	$stmt-&gt;bindValue(&apos;:id&apos;, $_GET[&quot;id&quot;]);
        ///	
        ///	$stmt-&gt;execute();
        ///	$row = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_detail {
            get {
                return ResourceManager.GetString("CRUDtemplate_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$#table#_rows=null;
        //////////////////////READ #table#
        ///	$find_sql = &quot;SELECT * FROM `#table#` order by #txt#&quot;;
        ///	$stmt      = $db-&gt;prepare($find_sql);
        ///	
        ///	$stmt-&gt;execute();
        ///	$#table#_rows = $stmt-&gt;fetchAll();
        //////////////////////READ #table#
        ///
        ///.
        /// </summary>
        internal static string CRUDtemplate_FK_Control_FILL {
            get {
                return ResourceManager.GetString("CRUDtemplate_FK_Control_FILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	///////////////////////////////////////////////////////////// FILL #table#
        ///	var jArray_#table# =   &lt;?php echo json_encode($#table#_rows); ?&gt;;
        ///
        ///	var combo_#table#_rows = &quot;&lt;option value=&apos;0&apos;&gt;&lt;/option&gt;&quot;;
        ///	for (var i = 0; i &lt; jArray_#table#.length; i++)
        ///	{
        ///		combo_#table#_rows += &quot;&lt;option value=&apos;&quot; + jArray_#table#[i][&quot;#PK#&quot;] + &quot;&apos;&gt;&quot; + jArray_#table#[i][&quot;#TXT#&quot;] + &quot;&lt;/option&gt;&quot;;
        ///	}
        ///
        ///	$(&quot;[name=#FK_NAME#]&quot;).html(combo_#table#_rows);
        ///	$(&quot;[name=#FK_NAME#]&quot;).change(); //select row 0 - no conflict on POST val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_FK_Control_FILL_COMBO {
            get {
                return ResourceManager.GetString("CRUDtemplate_FK_Control_FILL_COMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////	header(&quot;Location: index.html&quot;);
        /////	exit ;
        /////}
        ///
        ///$active_tab = &quot;#tblname#&quot;;
        ///
        ///if(#validation#){
        ///	echo &quot;error010101010&quot;;
        ///	return;
        ///}
        ///
        ///// include DB
        ///require_once (&apos;config.php&apos;);
        ///
        ///$db = connect();
        ///
        ///#checkboxes#
        ///
        ///#dtptimes#
        ///
        ///$ret_val=&quot;&quot;;
        ///if(isset($_POST[&apos;#tblname#FORM_updateID&apos;]) &amp;&amp; !empty($_POST[&apos;#tblname#FORM_updateID&apos;]))
        ///{
        ///	$sql = &quot;UPDATE `#tblname#` set #updateVAL# WHERE #updateWhere#=:#updateWhere#&quot;;
        ///	$stmt = $db-&gt;prepar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_save {
            get {
                return ResourceManager.GetString("CRUDtemplate_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$*field* = *0var*;
        ///
        ///if (isset($_POST[&apos;*field*&apos;])) {
        ///	if ($_POST[&apos;*field*&apos;] == &quot;on&quot;)
        ///		$*field* = 1;
        ///	else
        ///		$*field* = *0var*;
        ///}
        ///.
        /// </summary>
        internal static string CRUDtemplate_save_checkbox_validation {
            get {
                return ResourceManager.GetString("CRUDtemplate_save_checkbox_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$*field*=null;
        ///if (!empty($_POST[&apos;*field*&apos;]))
        ///{
        ///	$dt = DateTime::createFromFormat(&apos;d-m-Y&apos;, $_POST[&apos;*field*&apos;]);
        ///	
        ///	$*field* =	$dt-&gt;format(&apos;Y-m-d&apos;);
        ///}
        ///.
        /// </summary>
        internal static string CRUDtemplate_save_dtpmalot_validation {
            get {
                return ResourceManager.GetString("CRUDtemplate_save_dtpmalot_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///$*field*=null;
        ///if (!empty($_POST[&apos;*field*&apos;]))
        ///{
        ///	$dt = DateTime::createFromFormat(&apos;d-m-Y H:i&apos;, $_POST[&apos;*field*&apos;]);
        ///	
        ///	$*field* =	$dt-&gt;format(&apos;Y-m-d H:i:s&apos;);
        ///}
        ///.
        /// </summary>
        internal static string CRUDtemplate_save_dtptime_validation {
            get {
                return ResourceManager.GetString("CRUDtemplate_save_dtptime_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////session_start();
        /////
        /////if (!isset($_SESSION[&quot;u&quot;])) {
        /////	header(&quot;Location: index.html&quot;);
        /////	exit ;
        /////}
        ///
        ///$active_tab=&quot;#table#&quot;;
        ///
        ///require_once (&apos;template_top.php&apos;);
        ///
        ///// include DB
        ///require_once (&apos;config.php&apos;);
        ///
        ///$table_columns_caps = array(
        ///#fields#
        ///);
        ///
        ///$table_columns = array(
        ///#fields#
        ///);
        ///
        ///$db       = connect();
        ///
        ///$find_sql = &quot;SELECT #select# FROM `#table#`#joins#&quot;;
        ///
        ///$stmt      = $db-&gt;prepare($find_sql);
        ///$stmt-&gt;execute();
        ///$rows_sql = $stmt-&gt;fetchAll();
        ///$rows= array();
        ///
        ///forea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_table {
            get {
                return ResourceManager.GetString("CRUDtemplate_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///	&lt;!--http://glyphicons.bootstrapcheatsheets.com/--&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;title&gt;AdminLTE | Dashboard&lt;/title&gt;
        ///		&lt;meta content=&apos;width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no&apos; name=&apos;viewport&apos;&gt;
        ///		&lt;!-- bootstrap 3.0.2 --&gt;
        ///		&lt;link href=&quot;css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///		&lt;!-- Theme style --&gt;
        ///		&lt;link href=&quot;css/AdminLTE.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///		&lt;!-- Datatables style --&gt;
        ///		&lt;link href=&quot;css/datatables/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_top {
            get {
                return ResourceManager.GetString("CRUDtemplate_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 						&lt;li class=&quot;treeview &lt;?php if (isset($active_tab) &amp;&amp; $active_tab==&quot;#table#&quot;) echo &quot;active&quot;?&gt; &quot;&gt;
        ///							&lt;a href=&quot;#&quot;&gt; &lt;i class=&quot;glyphicon glyphicon-th-large&quot;&gt;&lt;/i&gt; &lt;span&gt;#table#&lt;/span&gt; &lt;i class=&quot;glyphicon pull-right glyphicon-chevron-right&quot;&gt;&lt;/i&gt; &lt;/a&gt;
        ///							&lt;ul class=&quot;treeview-menu&quot; style=&quot;display: none;&quot;&gt;
        ///								&lt;li &gt;
        ///									&lt;a href=&quot;tab_#table#.php&quot; style=&quot;margin-left: 10px;&quot;&gt;&lt;i class=&quot;glyphicon glyphicon-list&quot;&gt;&lt;/i&gt; List&lt;/a&gt;
        ///								&lt;/li&gt;
        ///								&lt;li &gt;
        ///									&lt;a href=&quot;tab_#table#_details.php [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRUDtemplate_top_item {
            get {
                return ResourceManager.GetString("CRUDtemplate_top_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document {
            get {
                object obj = ResourceManager.GetObject("document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_new {
            get {
                object obj = ResourceManager.GetObject("document_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export16 {
            get {
                object obj = ResourceManager.GetObject("export16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap helpEXCEL {
            get {
                object obj = ResourceManager.GetObject("helpEXCEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///if (**post validation**) {
        ///	echo &quot;error010101010&quot;;
        ///	return;
        ///}
        ///
        ///**bit validation**
        ///
        ///require_once (&apos;general.php&apos;);
        ///
        ///$db = connect();
        ///
        ///if ($stmt = $db -&gt; prepare(&quot;call **proc_name** (**q**)&quot;)) {
        ///
        ///	//bind our params
        ///	$stmt -&gt; bind_param(&apos;**s**&apos;, **bind_param**);
        ///	
        ///**bind_set**
        ///
        ///		/* Execute the prepared Statement */
        ///		$stmt -&gt; execute();
        ///
        ///		$g = $stmt -&gt; affected_rows;
        ///
        ///		if ($g == -1)
        ///			echo &quot;error&quot;;
        ///		else
        ///			echo &quot;ok&quot;;
        ///}
        ///
        /////close the statement
        ///$stmt -&gt; close();
        ///
        ///$db  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mySQLtunnelPHPproc_save {
            get {
                return ResourceManager.GetString("mySQLtunnelPHPproc_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nodeJS {
            get {
                object obj = ResourceManager.GetObject("nodeJS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if(#validation#){
        ///	header($_SERVER[&apos;SERVER_PROTOCOL&apos;] . &apos; 500 Internal Server Error&apos;, true, 500);
        ///	exit;
        ///}
        ///
        ///$db = connect();
        ///
        ///if(isset($_POST[&apos;#tblname#FORM_updateID&apos;]) &amp;&amp; !empty($_POST[&apos;#tblname#FORM_updateID&apos;]))
        ///{
        ///	$sql = &quot;UPDATE `#tblname#` set #updateVAL# WHERE #updateWhere#=:#updateWhere#&quot;;
        ///	$stmt = $db-&gt;prepare($sql);
        ///	$stmt-&gt;bindValue(&apos;:#updateWhere#&apos;, $_POST[&apos;#tblname#FORM_updateID&apos;]);
        ///}
        ///else
        ///{
        ///	$sql = &quot;INSERT INTO `#tblname#` (#insertFields#) VALUES (#insertVAL#)&quot;;
        ///	$stmt = $db-&gt;pre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PDOprepared {
            get {
                return ResourceManager.GetString("PDOprepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			&lt;li&gt;
        ///				&lt;a href=&quot;##table#TAB&quot; data-toggle=&apos;tab&apos;&gt;#table#&lt;/a&gt;
        ///			&lt;/li&gt;
        ///
        ///
        ///			&lt;div class=&quot;tab-pane fade&quot; id=&quot;#table#TAB&quot;&gt;
        ///				&lt;div id=&quot;#table#&quot;&gt;
        ///					&lt;?php
        ///					include (&apos;tab_#table#.php&apos;);
        ///					?&gt;
        ///				&lt;/div&gt;
        ///				&lt;div id=&quot;#table#_details&quot;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;.
        /// </summary>
        internal static string PHPpagesPORTAL {
            get {
                return ResourceManager.GetString("PHPpagesPORTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///session_start();
        ///
        ///if (!isset($_SESSION[&quot;u&quot;])) {
        ///	header(&quot;Location: index.html&quot;);
        ///	exit ;
        ///}
        ///?&gt;
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Portal&lt;/title&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///
        ///		&lt;link href=&quot;css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        /// 
        ///		&lt;script type=&apos;text/javascript&apos; src=&quot;js/jquery-1.10.2.min.js&quot;&gt;&lt;/script&gt;
        ///		&lt;script type=&apos;text/javascript&apos; src=&quot;js/bootstrap.min.js&quot;&gt;&lt;/sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesPORTALexample {
            get {
                return ResourceManager.GetString("PHPpagesPORTALexample", resourceCulture);
            }
        }
        
 
        internal static string PHPpagesPORTALprocedureDELETE_callexample {
            get {
                return ResourceManager.GetString("PHPpagesPORTALprocedureDELETE_callexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///
        ///if (!isset($_POST[&apos;comp_title&apos;]) || !isset($_POST[&apos;comp_name&apos;]) || !isset($_POST[&apos;cmp_password&apos;]) || !isset($_POST[&apos;page_editor&apos;]) || !isset($_POST[&apos;admin_name&apos;]) || !isset($_POST[&apos;comp_address&apos;]) || !isset($_POST[&apos;zipcode&apos;]) || !isset($_POST[&apos;area&apos;]) || !isset($_POST[&apos;phone_old&apos;]) || !isset($_POST[&apos;fax&apos;]) || !isset($_POST[&apos;email&apos;]) || !isset($_POST[&apos;url&apos;]) || !isset($_POST[&apos;member_group&apos;]) || !isset($_POST[&apos;member_international&apos;]) || !isset($_POST[&apos;member_syndicate&apos;]) || !isset($_POST[&apos;media_uni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesPORTALprocedureSAVE_callexample {
            get {
                return ResourceManager.GetString("PHPpagesPORTALprocedureSAVE_callexample", resourceCulture);
            }
        }
        
        internal static string PHPpagesPORTALprocedureSAVEexample {
            get {
                return ResourceManager.GetString("PHPpagesPORTALprocedureSAVEexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///session_start();
        ///
        ///if (!isset($_SESSION[&quot;u&quot;])) {
        ///	header(&quot;Location: index.html&quot;);
        ///	exit ;
        ///}
        ///?&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///	var last_**table**_Page;
        ///
        ///	function load_**table**_Records(page) {
        ///
        ///		$(&quot;#loading&quot;).height($(&apos;body&apos;).height());
        ///		$(&quot;#loading&quot;).show();
        ///
        ///		last_**table**_Page = page;
        ///
        ///		$.ajax({
        ///			type : &quot;GET&quot;,
        ///			url : &quot;tab_**table**_pagination.php&quot;,
        ///			data : {
        ///				page : page,
        ///				where : $(&quot;#**table**_search_combo&quot;).val(),
        ///				where_val : $(&quot;#**table**_search_tx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesSELECT {
            get {
                return ResourceManager.GetString("PHPpagesSELECT", resourceCulture);
            }
        }
        
        internal static string PHPpagesSELECTdetail {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;
        ///					&lt;input name=&apos;*field*&apos; class=&apos;form-control&apos; placeholder=&apos;*field*&apos;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;&lt;br&gt;
        ///					&lt;input type=&quot;checkbox&quot; name=&apos;*field*&apos;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_CHECK {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;
        ///					&lt;select id=&quot;*field*&quot; name=&apos;*field*&apos; class=&apos;form-control&apos;&gt;
        ///					&lt;/select&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_COMBO {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_COMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;&lt;br&gt;
        ///					&lt;input type=&quot;text&quot; class=&quot;form-control&quot; name=&quot;*field*&quot; data-date-format=&quot;yyyy-mm-dd&quot; style=&quot;width:100px&quot; &gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_DTP {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_DTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;&lt;br&gt;
        ///					&lt;input type=&quot;text&quot; name=&quot;*field*&quot; class=&quot;form-control&quot; data-date-format=&quot;dd-mm-yyyy&quot; readonly class=&quot;form_datetime&quot;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_DTPmalot {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_DTPmalot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;div class=&quot;col-xs-6 col-md-4&quot;&gt;
        ///				&lt;div class=&apos;form-group&apos;&gt;
        ///					&lt;label&gt;*field* :&lt;/label&gt;&lt;br&gt;
        ///					&lt;input type=&quot;text&quot; name=&quot;*field*&quot; class=&quot;form-control&quot; data-date-format=&quot;dd-mm-yyyy hh:ii&quot; readonly class=&quot;form_datetime&quot;&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///.
        /// </summary>
        internal static string PHPpagesSELECTdetailCOL_DTPtime {
            get {
                return ResourceManager.GetString("PHPpagesSELECTdetailCOL_DTPtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///session_start();
        ///
        ///if (!isset($_SESSION[&quot;u&quot;])) {
        ///    header(&quot;Location: index.html&quot;);
        ///    exit ;
        ///}
        ///
        ///// include your code to connect to DB.
        ///include (config.php&apos;);
        ///
        ///$conn = connect();
        ///
        /////your table name
        ///$tbl_name = &quot;**table**&quot;;
        ///
        ///// How many adjacent pages should be shown on each side?
        ///$adjacents = 3;
        ///
        ////*
        /// First get total number of rows in data table.
        /// If you have a WHERE clause in your query, make sure you mirror it here.
        /// */
        /// 
        ///$where = &quot;&quot;;
        ///if (isset($_GET[&apos;where&apos;]) &amp;&amp; isset($_GET [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPpagesSELECTpagination {
            get {
                return ResourceManager.GetString("PHPpagesSELECTpagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHPtemplate {
            get {
                object obj = ResourceManager.GetObject("PHPtemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHPtemplateCRUD {
            get {
                object obj = ResourceManager.GetObject("PHPtemplateCRUD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PHPtemplateCRUDbootstraptable {
            get {
                object obj = ResourceManager.GetObject("PHPtemplateCRUDbootstraptable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh24 {
            get {
                object obj = ResourceManager.GetObject("refresh24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templateCRUDadminLTE {
            get {
                object obj = ResourceManager.GetObject("templateCRUDadminLTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templateCRUDbootstraptable {
            get {
                object obj = ResourceManager.GetObject("templateCRUDbootstraptable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_marked {
            get {
                object obj = ResourceManager.GetObject("text_marked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///if (!isset($_POST[&quot;sql&quot;]) || !isset($_POST[&quot;p&quot;])) {
        ///	// if(!isset($_POST[&quot;sql&quot;]) || !isset($_POST[&quot;p&quot;])){
        ///	echo json_encode(&quot;Error: no token1&quot;);
        ///	return;
        ///	// }
        ///} else if ($_POST[&quot;p&quot;] != **password entered at desktop program**) {
        ///	echo json_encode(&quot;Error: no token2&quot;);
        ///	return;
        ///}
        ///
        ///$x = json_decode($_POST[&quot;sql&quot;]);
        ///
        ////////////////////////////////////////////////////////////////////////////////////////
        ///// 			SETUP MYSQL CONNECTION [START]
        ///////////////////////////////////////////////////////// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tunnelPHP {
            get {
                return ResourceManager.GetString("tunnelPHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///if (!isset($_POST[&quot;sql&quot;]) || !isset($_POST[&quot;p&quot;])) {
        ///	// if(!isset($_POST[&quot;sql&quot;]) || !isset($_POST[&quot;p&quot;])){
        ///	echo json_encode(&quot;Error: no token1&quot;);
        ///	return;
        ///	// }
        ///} else if ($_POST[&quot;p&quot;] != **password entered at desktop program**) {
        ///	echo json_encode(&quot;Error: no token2&quot;);
        ///	return;
        ///}
        ///
        ///$x = _json_decode($_POST[&quot;sql&quot;]);
        ///
        ////////////////////////////////////////////////////////////////////////////////////////
        ///// 			SETUP MYSQL CONNECTION [START]
        //////////////////////////////////////////////////////// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tunnelPHP_PDO {
            get {
                return ResourceManager.GetString("tunnelPHP_PDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////add it near connect tunnel PHP file with name trans.php
        ///if(!isset($_POST[&apos;statement&apos;]))
        ///{		echo json_encode(&quot;error - no token1&quot;);
        ///		return;}
        ///
        ///if(!isset($_POST[&apos;record&apos;]))
        ///{		echo json_encode(&quot;error - no token2&quot;);
        ///		return;
        ///} else if ($_POST[&quot;p&quot;] != **password entered at desktop program**) {
        ///	echo json_encode(&quot;error - wrong password&quot;);
        ///	return;
        ///}
        ///
        ///$json = json_decode($_POST[&apos;statement&apos;]);
        ///$statement = $json -&gt; q;
        ///
        ///
        ///$json = json_decode($_POST[&apos;record&apos;],TRUE);
        ///
        ///
        ///$params=array();
        ///$ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tunnelPHPtrans {
            get {
                return ResourceManager.GetString("tunnelPHPtrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        /////add it near connect tunnel PHP file with name trans_batch.php
        ///
        ///if (!isset($_POST[&apos;statement&apos;])) {		echo json_encode(&quot;error - no token1&quot;);
        ///	return;
        ///}
        ///
        ///if (!isset($_POST[&apos;records&apos;])) {		echo json_encode(&quot;error - no token2&quot;);
        ///	return;
        ///} else if ($_POST[&quot;p&quot;] != **password entered at desktop program**) {
        ///	echo json_encode(&quot;error - wrong password&quot;);
        ///	return;
        ///}
        ///
        ///$json = json_decode($_POST[&apos;statement&apos;]);
        ///$statement = $json -&gt; q;
        ///
        ///$json = json_decode($_POST[&apos;records&apos;], TRUE);
        ///
        /////////////// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tunnelPHPtransBATCH {
            get {
                return ResourceManager.GetString("tunnelPHPtransBATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window {
            get {
                object obj = ResourceManager.GetObject("window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows {
            get {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
